---
title: "R Notebook"
output: html_notebook
author: apawlik
---

Required packages
```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
library(xlsx)
library(janitor)
options(stringsAsFactors = FALSE)
```

Read CSV into data frames (historic data only)
```{r}
weather_78_89 <- read.csv("raw/Daily_Weather_Raw_1978-1989.csv")
weather_90_16 <- read.csv("raw/Daily_Weather_Raw_1990-2016.csv")

# check that data imported correctly
glimpse(weather_78_89)
glimpse(weather_90_16)
```

Fix dates and remove unwanted rows and columns
```{r}
# put dates in ymd (figure out how to add first part of year number)

# expect 13 columns

```


Read Excel files of recent data
```{r}
# 32 as of May 2020, excludes notes sheet
num_sheets <- 32

# column types
columnTypes <- c("Date")

# make a list of monthly sheets beginning with oldest 2 months (so month indices won't change)
l1 <- read.xlsx("raw/Daily_Weather_Raw_2017-Present.xlsx", num_sheets, colClasses = columnTypes, endRow = 32)
l2 <- read.xlsx("raw/Daily_Weather_Raw_2017-Present.xlsx", num_sheets - 1, colClasses = columnTypes, endRow = 32)
weather_17_pres <- list(l1, l2)
for (i in (num_sheets - 2):2) {  # exclude current month(incomplete data)
  l <- read.xlsx("raw/Daily_Weather_Raw_2017-Present.xlsx", i, colClasses = columnTypes, endRow = 32)
  weather_17_pres <- append(weather_17_pres, list(l))
}

# check that data imported correctly
num_months <- num_sheets - 1  # exclude current month (incomplete data)
# for (i in 1:num_months) {
#   glimpse(weather_17_pres[[i]])
# }
```

Fix times in monthly data
```{r}
# convert datetimes from Time column back to just times
for (i in 1:num_months) {
  weather_17_pres[[i]]$Time <- format(strptime(weather_17_pres[[i]]$Time, "%Y-%m-%d %H:%M:%S"), "%H:%M")
  # print(weather_17_pres[[i]][2])
}
```

Clean monthly data 2017-present before combining into single data frame
```{r}
# check that each has correct number of rows and columns before combining
num_cols <- 17  # last column in excel sheet is Q

# remove columns outside num_cols
for (i in 1:num_months) {
  # oct2018 contains an extra column?
  if (i == 13) {  
    weather_17_pres[[i]] <- weather_17_pres[[i]][1:(num_cols + 1)]
  } else {
    weather_17_pres[[i]] <- weather_17_pres[[i]][1:num_cols]
  }
}

# remove rows beyond number of days in that month
for (i in 1:num_months) {
  n <- days_in_month(as.Date(weather_17_pres[[i]][10, 1], "%Y-%m-%d"))
  names(n) <- NULL  # convert from named int to just int
  weather_17_pres[[i]] <- weather_17_pres[[i]][1:n, ]
}
```

Combine historic data with monthly into final data frame
```{r}

```

Check bounds on all data fields
```{r}

```

Export
```{r}

```
